# Streamlit Cloud デプロイメント用設定
# 本ファイルはStreamlit Cloudの「Secrets」セクションに設定してください

# 統一環境認証パスワード
BETA_PASSWORD = "ruri2024beta"
DEVELOPER_PASSWORD = "aiTuberDev2024"
ADMIN_PASSWORD = "ruriSuperAdmin2024"

# デフォルトユーザーレベル (PUBLIC/BETA/DEVELOPER/ADMIN)
DEFAULT_USER_LEVEL = "PUBLIC"

# 機能フラグ
ENABLE_AI_FEATURES = true
ENABLE_IMAGE_PROCESSING = true
ENABLE_OBS_INTEGRATION = false
ENABLE_STREAMING_FEATURES = false

# デバッグモード
DEBUG_MODE = false
SHOW_TECHNICAL_DETAILS = false

# アプリケーション設定
APP_ENVIRONMENT = "production"