# Streamlit Cloud デプロイメント用設定
# 本ファイルはStreamlit Cloudの「Secrets」セクションに設定してください
# ⚠️ 注意: この内容は.gitignoreに追加されています（公開されません）

# 所有者認証パスワード（強力なパスワードに変更してください）
OWNER_PASSWORD = ""

# OpenAI API設定（オプション）
OPENAI_API_KEY = ""

# デフォルトユーザーレベル (PUBLIC/OWNER)
DEFAULT_USER_LEVEL = "PUBLIC"

# 機能フラグ
ENABLE_AI_FEATURES = true
ENABLE_IMAGE_PROCESSING = true
ENABLE_OBS_INTEGRATION = false
ENABLE_STREAMING_FEATURES = false

# デバッグモード
DEBUG_MODE = false
SHOW_TECHNICAL_DETAILS = false

# アプリケーション設定
APP_ENVIRONMENT = "production"